---
title: "data processing"
author: "Shijing Zhou"
date: "12/11/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(randomForest)
library(ISLR)
library(psych)
library(corrplot)
library(rpart)
library(MASS)
library(pROC)
library(gbm)
```


## Data Import
```{r}
wine <- readr::read_csv("https://raw.githubusercontent.com/shijing-z/EDLD654-Final-Project/main/data/winequality-red.csv")
```

## Transform a continous outcome into a binary outcome
```{r}
wine$quality <- I(wine$quality > 6) * 1
# 1 = Good quality 
# 0 = Bad quality
```

## Split training and test dataset 

```{r}
set.seed(960604) 
X <- scale(wine[,1:11])
tst <- 1:599
train <- wine[-tst,]
test <- wine[tst,]
```

## Model 1: Logistic Regression

```{r}
glm <- glm(quality ~ ., family="binomial", data=train)
summary(glm)
test$yhat.glm <- predict(glm, test, type="response")

TPR <- function(y,yhat)  { sum(y==1 & yhat==1) / sum(y==1) }
TNR <- function(y,yhat)  { sum(y==0 & yhat==0) / sum(y==0) }

TPR(test$quality, (test$yhat.glm > 0.5))
TNR(test$quality, (test$yhat.glm > 0.5))
glm.roc <- roc(test$quality, test$yhat.glm, direction="<")
plot(glm.roc)
```

## Model 2: Decision Tree 
```{r}
#Decision tree 1
form1 <- formula(quality~.)
t1 <- rpart(form1, data=train, cp= .001, method="class")
plot(t1,uniform=T,compress=T,margin=.05,branch=0.3)
text(t1, cex=.7, col="navy",use.n=TRUE)

plotcp(t1)
CP <- printcp(t1)

#Decision tree 2 based on tree 1
t2 <- prune(t1,cp = CP[6, 1])
plot(t2,uniform=T,compress=T,margin=.05,branch=0.3)
text(t2, cex=.7, col="navy",use.n=TRUE)

#calculate the yhat table and TPR
yhat.t2 <- predict(t2, test, type="prob")[,2]
table(yhat.t2>0.5, test$quality)
TPR(yhat.t2>0.5, test)

#create ROC
t2.roc <- roc(test$quality, yhat.t2, direction = "<")
t2.roc
plot(t2.roc, lwd=3)
```

## Model 3: Random Forest
```{r}
#set parameters
Y <- factor(train$quality)
X <- as.matrix(train[,1:11])

#set random tree
mtry <- round(ncol(X)^.5); 
ntree <- 1000
rf1 <- randomForest(x=X, y=Y, ntree=ntree, mtry=mtry, importance=TRUE)
rf1

summary(rf1)
names(rf1)

importance(rf1)

varImpPlot(rf1)

#Evaluate the predictions
pred.rf1 <- predict(rf1, test)
table(pred.rf1, test$quality)

yhat.rf1 <- predict(rf1, test, type="prob")[,2]

rf1.roc <- roc(test$quality, yhat.rf1, direction="<")
rf1.roc
plot(rf1.roc, lwd=3, col = "grey")
```

## Plot

```{r}
lines(glm.roc, lwd=2, col = "green")
lines(t2.roc, lwd=2, col = "yellow")
lines(rf1.roc, lwd=2, col = "red")
legend("bottomright",
       title="ROC Curves",c("glm","tree","random forest"), 
       fill=c("green","yellow","red"))
```

